eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #    hostname: ConsumerName

#server:
#  port: 8091

#provider:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

spring:
  application:
    name: consumer
  cloud:
    stream:
      bindings:
        input:
          group: consumer
          destination: StreamExchange
          content-type: application/json
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

env: 
  dev
